# Generated by Django 4.2.3 on 2023-07-06 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('siret', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=64)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'entreprise',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=128)),
                ('prenom', models.CharField(blank=True, max_length=64)),
                ('num_tel', models.CharField(blank=True, max_length=10)),
                ('password', models.CharField(max_length=258)),
                ('is_admin', models.BooleanField(default=False)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperless.entreprise')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32, unique=True)),
                ('state', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperless.user')),
            ],
            options={
                'db_table': 'facture',
            },
        ),
    ]
