# Generated by Django 4.1.7 on 2023-06-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facture',
            table='facture',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
