# Generated by Django 4.2.3 on 2023-07-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
