# Generated by Django 4.2.2 on 2023-07-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paperless", "0002_alter_facture_table_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="state",
            field=models.CharField(default="EN_COURS", max_length=32),
            preserve_default=False,
        ),
    ]
