# Generated by Django 4.2.2 on 2023-07-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0002_entreprise_valide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='location',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
