# Generated by Django 4.2.2 on 2023-07-16 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0003_alter_facture_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='taille',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='nom',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
