# Generated by Django 4.2.2 on 2023-07-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paperless", "0003_facture_state"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="factures",),
        migrations.AddField(
            model_name="facture",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="paperless.user",
            ),
            preserve_default=False,
        ),
    ]
