# Generated by Django 4.1.1 on 2023-07-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paperless", "0003_alter_facture_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="is_updated",
            field=models.BooleanField(default=False),
        ),
    ]
