# Generated by Django 4.2.3 on 2023-07-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0004_remove_user_factures_facture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='location',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
