# Generated by Django 4.2.2 on 2023-07-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0005_facture_date_facture_taille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='location',
            field=models.CharField(max_length=128),
        ),
    ]
