# Generated by Django 4.2.2 on 2023-07-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0006_alter_facture_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='location',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
